### ISSUE TITLE
Improving the register function

### ISSUE THREAD

**Issue by luxcem** [thanxngo/redux-crudo#3]
Right now the `apiActionType` have a `register` method to register a new action linked to an API call.

I found it confusing : 
```javascript
FeedbackActions.register("list", FeedbackApi.list, "list");
```

There is twice the "list" word, `register` is part of the object `FeedbackActions` but it's not an action.

What I suggest: 

1. Rename `apiActionType()` to `apiActions()` since reducer is only `apiReducer()`.
2. Extract the `register` method in something else that will work like that:

```javascript
// Given that Services.Feedback.list is the api call method
FeedbackActions.list = assignApiToList(FeedbackActions, Services.Feedback.list);
```

The drawback of that is that we have a function for every method (Create, Read, Update, Delete, List, Post)

An other solution would be to have a constant for each method:

```javascript
// Given that Services.Feedback.list is the api call method
FeedbackActions.list = assignApiMethod(FeedbackActions, Services.Feedback.list, LIST);
```

The `assignXXX` method needs the FeedbackActions object to correctly dispatch the "Request", "Success" and "Failure" actions.

**Comment by nsuarezcanton** [comment]
```
FeedbackActions.list = assignApiMethod(FeedbackActions, Services.Feedback.list, LIST);
```
This appears to me as the clearer syntax. Also, I'd suggest changing `assignApiMethod` to `assignCrudOperation` or `assignCrudMethod`.
