### ISSUE TITLE
Actions should follow the FSA standard

### ISSUE THREAD

**Issue by luxcem** [thanxngo/redux-crudo#8]
https://github.com/redux-utilities/flux-standard-action

**Comment by Rolandkuku** [comment]
From FSA's doc:
> By convention, if error is true, the payload SHOULD be an error object. This is akin to rejecting a promise with an error object.

But our base state structure is like so:

```
const initialState = {
        args: {},
        item: {},
        items: new Map(),
        error: false,
        errors: {},
        loading: false,
        status: "",
        statusCode: 0,
    };
```

If the entire payload is an error, the front would not display any data except the error. @floriancargoet @luxcem

**Comment by luxcem** [comment]
It's hard to only have error object in the payload, we will still need the loading boolean for example.

**Comment by Rolandkuku** [comment]
This is my opinion too.

**Comment by floriancargoet** [comment]
payload != state

**Comment by Rolandkuku** [comment]
Ok then maybe something like this ?

```
const noErrorState = {
        args: {},
        item: {},
        items: new Map(),
        error: false,
        errorDetails: null,
        loading: false,
        status: "",
        statusCode: 0,
    };

const errorState = {
       // ...
        error: false,
        errorDetails: new Error(/* whatever */),
    };
```

**Comment by floriancargoet** [comment]
I mean, FSA doesn't tell you what to put in your state, only the shape of your action.
So your action is { error: true, payload : Error } and your reducer does what you want.

**Comment by floriancargoet** [comment]
We don't have to change anything on the reducer side.

**Comment by Rolandkuku** [comment]
👍
